#!/bin/bash

#sleep 300
mkfs.ext4 /dev/xvdx
mkfs.ext4 /dev/xvdy
mkfs.ext4 /dev/xvdz

echo "/dev/xvdx /opt ext4 defaults.nofail 0 0" >> /etc/fstab
echo "/dev/xvdy /mnt ext4 defaults.nofail 0 0" >> /etc/fstab
echo "/dev/xvdz /media ext4 defaults.nofail 0 0" >> /etc/fstab

sleep 10
mount -a

